server:
  port: ":9091"

vision:
  provider: "yolo"
  endpoint: "http://localhost:5000"
  # provider: "qwen"
  # api_key: "sk-c8454d49077c4827a2919b023283d588"
  # endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  # model: "qwen3.6-plus-2026-04-02"
