server:
  port: ":9091"

vision:
  provider: "yolo"
  endpoint: "http://localhost:5000"

mysql:
  dsn: "mtian_o:PBFHBNYrABBnd37C@tcp(8.134.104.226:3306)/mtian_o?charset=utf8mb4&parseTime=True"

wechat:
  appid: "wxf09f11a3eccbaac1"
  secret: "a7015eef960f6907d9aa0c6e4191f29e"

jwt:
  secret: "p8cBsPn7IN1wWrkEHje4"
  expire_hours: 168

stock:
  akshare_endpoint: "http://localhost:5001"
  ai_model: "qwen-plus"
  ai_api_key: "sk-c8454d49077c4827a2919b023283d588"
  ai_endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1"
